name          'example42-mariadb'
version       '3.0.0-alpha1'
source        'https://github.com/example42/puppet-mariadb'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and manages mariadb'
description   'This module installs and manages mariadb'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
